export const PROPERTY_FETCH_PENDING = "PROPERTY_FETCH_PENDING";
export const PROPERTY_FETCH_COMPLETE = "PROPERTY_FETCH_COMPLETE";
export const PROPERTY_FETCH_ERROR = "PROPERTY_FETCH_ERROR";

export const DRAFT_FETCH_PENDING = "DRAFT_FETCH_PENDING";
export const DRAFT_FETCH_COMPLETE = "DRAFT_FETCH_COMPLETE";
export const DRAFT_FETCH_ERROR = "DRAFT_FETCH_ERROR";

export const PG_FETCH_PENDING = "PG_FETCH_PENDING";
export const PG_FETCH_COMPLETE = "PG_FETCH_COMPLETE";
export const PG_FETCH_ERROR = "PG_FETCH_ERROR";

export const RECEIPT_FETCH_ERROR = "RECEIPT_FETCH_ERROR";
export const RECEIPT_FETCH_COMPLETE = "RECEIPT_FETCH_COMPLETE";
export const RECEIPT_FETCH_PENDING = "RECEIPT_FETCH_PENDING";
