export const ASSESSMENT_FETCH_PENDING = "ASSESSMENT_FETCH_PENDING";
export const ASSESSMENT_FETCH_COMPLETE = "ASSESSMENT_FETCH_COMPLETE";
export const ASSESSMENT_FETCH_ERROR = "ASSESSMENT_FETCH_ERROR";
