var dat = {
    'works.search': {
      numCols: 6,
      useTimestamp: true,
      objectName: 'RemarksRequest',
      url: '/works-masters/v1/remarks/_search',
      groups: [
        {
          name: 'search',
          label: 'works.remarks.search.title',
          fields: [
            {
              name: 'typeOfDocument',
              jsonPath: 'typeOfDocument',
              label: 'works.remarks.label.typeOfDocument',
              type: 'singleValueList',
              isRequired: false,
              isDisabled: false,
              url: '/egov-mdms-service/v1/_get?&moduleName=Works&masterName=TypeOfDocument|$..code|$..code',
              patternErrorMsg: 'works.remarks.error.message.typeOfDocument',
            },
            {
                name: 'remarksType',
                jsonPath: 'remarksType',
                label: 'works.remarks.label.remarksType',
                type: 'singleValueList',
                isRequired: false,
                isDisabled: false,
                url: '/egov-mdms-service/v1/_get?&moduleName=Works&masterName=RemarksType|$..code|$..code',
                patternErrorMsg: 'works.remarks.error.message.remarksType',
            },
            {
                name: 'remarksDescription',
                jsonPath: 'remarksDescription',
                label: 'works.remarks.label.remarksDescription',
                type: 'text',
                isRequired: false,
                isDisabled: false,
                patternErrorMsg: 'works.remarks.error.message.remarksDescription',
            },
          ],
        },
      ],
      result: {
        header: [
          {
            label: 'works.search.result.code',
          },
          {
            label: 'works.search.result.documenttype',
          },
          {
            label: 'works.search.result.description',
          },
          {
            label: 'works.search.result.type',
          },
        ],
        values: ['code', 'description', 'scheduleCategory.code', 'uom.code'],
        resultIdKey: 'code',
        resultPath: 'remarks',
        rowClickUrlUpdate: '/update/works/remarks/{code}',
        rowClickUrlView: '/view/works/remarks/{code}',
      },
    },
    'works.create': {
      numCols: 12/2,
      useTimestamp: true,
      objectName: 'remarks',
      idJsonPath: 'remarks[0].id',
      injectData: [
        {
          jsonPath: 'remarks[0].remarksDetails[0].tenantId',
          value: localStorage.getItem('tenantId'),
        },
        {
          jsonPath: 'remarks[0].remarksDetails[0].tenantId',
          value: localStorage.getItem('tenantId'),
        },
      ],
      groups: [
        {
          name: 'remarkMasterCreate',
          label: 'works.create.group.title.createRemarkMaster',
          fields: [
            {
                name: 'typeOfDocument',
                jsonPath: 'remarks[0].typeOfDocument',
                label: 'works.remarks.label.typeOfDocument',
                type: 'singleValueList',
                isRequired: true,
                isDisabled: false,
                defaultValue: '',
                maxLength: 100,
                minLength: 1,
                url: '/egov-mdms-service/v1/_get?&moduleName=Works&masterName=TypeOfDocument|$..code|$..code',
                patternErrorMsg: 'works.remarks.error.message.typeOfDocument',
            },
            
            {
                name: 'remarksType',
                jsonPath: 'remarks[0].remarksType',
                label: 'works.remarks.label.remarksType',
                type: 'singleValueList',
                isRequired: true,
                isDisabled: false,
                defaultValue: '',
                maxLength: 100,
                minLength: 1,
                url: '/egov-mdms-service/v1/_get?&moduleName=Works&masterName=RemarksType|$..code|$..code',
                patternErrorMsg: 'works.remarks.error.message.remarksType',
            },
          ],
        },
        {
            name: 'Rate Details',
            label: 'works.rate.details.label.title',
            fields: [
              {
                type: 'tableList',
                jsonPath: 'remarks[0].remarksDetails[0]',
                tableList: {
                  header: [
                    {
                      label: 'works.rate.details.label.remark',
                    },
                    {
                        label: 'works.rate.details.label.remarksDescription',
                    },
                    {
                        label: 'works.rate.details.label.editable',
                    },
                  ],
                  values: [
                    {
                      name: 'remarks',
                      pattern: '',
                      type: 'text',
                      jsonPath: 'remarks[0].remarksDetails[0].remarks',
                      displayJsonPath: 'remarks[0].remarksDetails[0].remarks',
                      isRequired: true,
                      isDisabled: false,
                    },
                    {
                        name: 'remarksDescription',
                        pattern: '',
                        type: 'text',
                        jsonPath: 'remarks[0].remarksDetails[0].remarksDescription',
                        displayJsonPath: 'remarks[0].remarksDetails[0].remarksDescription',
                        isRequired: true,
                        isDisabled: false,
                    },
                    {
                        name: 'editable',
                        pattern: '',
                        type: 'checkbox',
                        jsonPath: 'remarks[0].remarksDetails[0].editable',
                        displayJsonPath: 'remarks[0].remarksDetails[0].editable',
                        isRequired: false,
                        isDisabled: false,
                    },
                  ],
                },
              },
            ],
        },
      ],
      url: '/works-masters/v1/remarks/_create',
      tenantIdRequired: true,
    },
    'works.view': {
      numCols: 4,
      useTimestamp: true,
      objectName: 'scheduleOfRates',
      groups: [
        {
          name: 'createRateMaster',
          label: 'works.create.group.title.createRateMaster',
          fields: [
            {
              name: 'code',
              jsonPath: 'scheduleOfRates[0].scheduleCategory.code',
              label: 'works.create.scheduleCategory',
              pattern: '[a-zA-Z0-9-\\\\]+',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              patternErrorMsg: 'works.create.field.message.code',
              url: '/egov-mdms-service/v1/_get?&moduleName=Works&masterName=ScheduleCategory|$..code|$..code',
            },
            {
              name: 'code',
              jsonPath: 'scheduleOfRates[0].code',
              label: 'works.create.code',
              pattern: '[a-zA-Z0-9-\\\\]+',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              patternErrorMsg: 'works.create.field.message.code',
            },
            {
              name: 'description',
              jsonPath: 'scheduleOfRates[0].description',
              label: 'works.create.description',
              pattern: '[0-9a-zA-Z_@./#&+-/!(){}",^$%*|=;:<>?`~ ]+',
              type: 'textarea',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 4000,
              minLength: 1,
              patternErrorMsg: 'works.create.field.message.description',
            },
            {
              name: 'code',
              jsonPath: 'scheduleOfRates[0].uom.code',
              label: 'works.create.uom',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              maxLength: 30,
              minLength: 1,
              patternErrorMsg: '',
              url: '/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Uom|$..code|$..code',
            },
          ],
        },
        {
          name: 'rateDetails',
          label: 'works.create.group.title.rateDetails',
          fields: [
            {
              name: '',
              label: '',
              type: 'multiFieldAddToTable',
              jsonPath: 'scheduleOfRates[0].sorRates',
              header: [
                {
                  label: 'Rate',
                },
                {
                  label: 'FromDate',
                },
                {
                  label: 'ToDate',
                },
              ],
              values: [
                {
                  name: 'rate',
                  jsonPath: 'scheduleOfRates[0].sorRates[0].rate',
                  label: 'Rate',
                  type: 'text',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'FromDate',
                  jsonPath: 'scheduleOfRates[0].sorRates[0].fromDate',
                  label: 'FromDate',
                  type: 'datePicker',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'ToDate',
                  jsonPath: 'scheduleOfRates[0].sorRates[0].toDate',
                  label: 'ToDate',
                  type: 'datePicker',
                  isRequired: false,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
              ],
            },
          ],
        },
        {
          name: 'marketRateDetails',
          label: 'works.create.group.title.marketRateDetails',
          fields: [
            {
              name: '',
              label: '',
              type: 'multiFieldAddToTable',
              jsonPath: 'scheduleOfRates[0].marketRates',
              header: [
                {
                  label: 'Rate',
                },
                {
                  label: 'FromDate',
                },
                {
                  label: 'ToDate',
                },
              ],
              values: [
                {
                  name: 'rate',
                  jsonPath: 'scheduleOfRates[0].marketRates[0].rate',
                  label: 'Rate',
                  type: 'text',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'FromDate',
                  jsonPath: 'scheduleOfRates[0].marketRates[0].fromDate',
                  label: 'FromDate',
                  type: 'datePicker',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'ToDate',
                  jsonPath: 'scheduleOfRates[0].marketRates[0].toDate',
                  label: 'ToDate',
                  type: 'datePicker',
                  isRequired: false,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
              ],
            },
          ],
        },
      ],
      tenantIdRequired: true,
      url: '/works-masters/v1/scheduleofrates/_search?sorCodes={code}',
    },
    'works.update': {
      numCols: 4,
      useTimestamp: true,
      objectName: 'scheduleOfRates',
      injectData: [
        {
          jsonPath: 'scheduleOfRates[0].sorRates[0].tenantId',
          value: localStorage.getItem('tenantId'),
        },
        {
          jsonPath: 'scheduleOfRates[0].marketRates[0].tenantId',
          value: localStorage.getItem('tenantId'),
        },
      ],
      groups: [
        {
          name: 'createRateMaster',
          label: 'works.create.group.title.createRateMaster',
          fields: [
            {
              name: 'code',
              jsonPath: 'scheduleOfRates[0].scheduleCategory.code',
              label: 'works.create.code',
              pattern: '[a-zA-Z0-9-\\\\]+',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              patternErrorMsg: 'works.create.field.message.code',
              url: '/egov-mdms-service/v1/_get?&moduleName=Works&masterName=ScheduleCategory|$..code|$..code',
            },
            {
              name: 'code',
              jsonPath: 'scheduleOfRates[0].code',
              label: 'works.create.code',
              pattern: '[a-zA-Z0-9-\\\\]+',
              type: 'text',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 100,
              minLength: 1,
              patternErrorMsg: 'works.create.field.message.code',
            },
            {
              name: 'description',
              jsonPath: 'scheduleOfRates[0].description',
              label: 'works.create.description',
              pattern: '[0-9a-zA-Z_@./#&+-/!(){}",^$%*|=;:<>?`~ ]+',
              type: 'textarea',
              isRequired: true,
              isDisabled: false,
              defaultValue: '',
              maxLength: 4000,
              minLength: 1,
              patternErrorMsg: 'works.create.field.message.description',
            },
            {
              name: 'code',
              jsonPath: 'scheduleOfRates[0].uom.code',
              label: 'works.create.code',
              pattern: '',
              type: 'text',
              isRequired: false,
              isDisabled: false,
              defaultValue: '',
              maxLength: 30,
              minLength: 1,
              patternErrorMsg: '',
              url: '/egov-mdms-service/v1/_get?&moduleName=common-masters&masterName=Uom|$..code|$..code',
            },
          ],
        },
        {
          name: 'rateDetails',
          label: 'works.create.group.title.rateDetails',
          fields: [
            {
              name: '',
              label: '',
              type: 'multiFieldAddToTable',
              jsonPath: 'scheduleOfRates[0].sorRates',
              header: [
                {
                  label: 'Rate',
                },
                {
                  label: 'FromDate',
                },
                {
                  label: 'ToDate',
                },
              ],
              values: [
                {
                  name: 'rate',
                  jsonPath: 'scheduleOfRates[0].sorRates[0].rate',
                  label: 'Rate',
                  type: 'text',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'FromDate',
                  jsonPath: 'scheduleOfRates[0].sorRates[0].fromDate',
                  label: 'FromDate',
                  type: 'datePicker',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'ToDate',
                  jsonPath: 'scheduleOfRates[0].sorRates[0].toDate',
                  label: 'ToDate',
                  type: 'datePicker',
                  isRequired: false,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
              ],
            },
          ],
        },
        {
          name: 'marketRateDetails',
          label: 'works.create.group.title.marketRateDetails',
          fields: [
            {
              name: '',
              label: '',
              type: 'multiFieldAddToTable',
              jsonPath: 'scheduleOfRates[0].marketRates',
              header: [
                {
                  label: 'Rate',
                },
                {
                  label: 'FromDate',
                },
                {
                  label: 'ToDate',
                },
              ],
              values: [
                {
                  name: 'rate',
                  jsonPath: 'scheduleOfRates[0].marketRates[0].rate',
                  label: 'Rate',
                  type: 'text',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'FromDate',
                  jsonPath: 'scheduleOfRates[0].marketRates[0].fromDate',
                  label: 'FromDate',
                  type: 'datePicker',
                  isRequired: true,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
                {
                  name: 'ToDate',
                  jsonPath: 'scheduleOfRates[0].marketRates[0].toDate',
                  label: 'ToDate',
                  type: 'datePicker',
                  isRequired: false,
                  isDisabled: false,
                  maxLength: 128,
                  minLength: 1,
                  patternErrorMsg: '',
                },
              ],
            },
          ],
        },
      ],
      url: '/works-masters/v1/scheduleofrates/_update',
      tenantIdRequired: true,
      searchUrl: '/works-masters/v1/scheduleofrates/_search?ids={ids}',
    },
  };
  export default dat;
  