const formConfig = {
  name: "additionalRebate",
  fields: {
    adhocPenalty: {
      id: "adhocPenalty",
      type: "number",
      floatingLabelText: "Additional Charges",
      hintText: "Enter amount",
      required: false,
      fullWidth: true,
      jsonPath: "Properties[0].propertyDetails[0].adhocPenalty",
    },
    adhocPenaltyReason: {
      id: "adhocPenaltyReason",
      type: "singleValueList",
      dropDownData: [
        { label: "Pending dues from earlier", value: "Pending dues from earlier" },
        { label: "Miscalculation of earlier assessment", value: "Miscalculation of earlier assessment" },
        { label: "One time Penalty", value: "One time Penalty" },
        { label: "Others", value: "Others" },
      ],
      floatingLabelText: "Reason for Charges",
      hintText: "Select",
      required: false,
      fullWidth: true,
      jsonPath: "Properties[0].propertyDetails[0].adhocPenaltyReason",
    },
    adhocExemption: {
      id: "adhocExemption",
      type: "number",
      floatingLabelText: "Additional Rebate",
      hintText: "Enter amount",
      required: false,
      fullWidth: true,
      jsonPath: "Properties[0].propertyDetails[0].adhocExemption",
    },
    adhocExemptionReason: {
      id: "adhocExemptionReason",
      type: "singleValueList",
      floatingLabelText: "Reason for rebate",
      hintText: "Select",
      dropDownData: [
        { label: "Advanced paid by citizen earlier", value: "Advanced paid by citizen earlier" },
        { label: "Rebate provided by commissioner/EO", value: "Rebate provided by commissioner/EO" },
        { label: "Additional amount charged from the citizen", value: "Additional amount charged from the citizen" },
        { label: "Others", value: "Others" },
      ],
      required: false,
      fullWidth: true,
      jsonPath: "Properties[0].propertyDetails[0].adhocExemptionReason",
    },
    otherExemptionReason: {
      id: "adhocExemption",
      type: "textField",
      floatingLabelText: "Description",
      hintText: "Enter a description of the reason",
      required: false,
      fullWidth: true,
      jsonPath: "Properties[0].propertyDetails[0].adhocExemptionReason",
    },
    otherPenaltyReason: {
      id: "adhocExemption",
      type: "textField",
      floatingLabelText: "Description",
      hintText: "Enter a description of the reason",
      required: false,
      fullWidth: true,
      jsonPath: "Properties[0].propertyDetails[0].adhocPenaltyReason",
    },
  },
  action: "",
  saveUrl: "",
  redirectionRoute: "",
};

export default formConfig;
