export const COMPLAINTS_FETCH_PENDING = "COMPLAINTS_FETCH_PENDING";
export const COMPLAINTS_FETCH_COMPLETE = "COMPLAINTS_FETCH_COMPLETE";
export const COMPLAINTS_FETCH_ERROR = "COMPLAINTS_FETCH_ERROR";
export const SET_COMPLAINTS_CATEGORIS="SET_COMPLAINTS_CATEGORIS";
