export const SET_DROPDOWN_DATA = "SET_DROPDOWN_DATA";
export const SET_CITIES = "SET_CITIES";
export const EMPLOYEE_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";
export const EMPLOYEE_FETCH_ERROR = "EMPLOYEE_FETCH_ERROR";
export const CITIZEN_FETCH_SUCCESS = "CITIZEN_FETCH_SUCCESS";
export const CITIZEN_FETCH_ERROR = "CITIZEN_FETCH_ERROR";
export const DEPARTMENT_AND_DESIGNATION_FETCH_ERROR = "DEPARTMENT_AND_DESIGNATION_FETCH_ERROR";
export const DEPARTMENT_AND_DESIGNATION_FETCH_SUCCESS = "DEPARTMENT_AND_DESIGNATION_FETCH_SUCCESS";
