import React, { Component } from "react";
import formHoc from "egov-ui-kit/hocs/form";
import { Screen } from "modules/common";
import SearchPropertyForm from "./components/SearchPropertyForm";
import PropertyTable from "./components/PropertyTable";
import { validateForm } from "egov-ui-kit/redux/form/utils";
import { displayFormErrors } from "egov-ui-kit/redux/form/actions";
import { connect } from "react-redux";
import { httpRequest } from "egov-ui-kit/utils/api";
import { Button } from "components";
import "./index.css";

const PropertySearchFormHOC = formHoc({ formKey: "searchProperty", path: "PropertyTaxPay" })(SearchPropertyForm);

class SearchProperty extends Component {
  constructor(props) {
    super(props);
    this.state = {
      searchResult: [],
    };
  }
  onSearchClick = (form, formKey) => {
    if (!validateForm(form)) {
      this.props.displayFormErrors(formKey);
    } else {
      const { city, ids, name, oldAssessmentNumber, mobileNumber } = form.fields || {};
      const queryParams = [];
      if (city.value) {
        queryParams.push({ key: "tenantId", value: city.value });
      }
      if (ids.value) {
        queryParams.push({ key: "ids", value: ids.value });
      }
      if (name.value) {
        queryParams.push({ key: "name", value: name.value });
      }
      if (oldAssessmentNumber.value) {
        queryParams.push({ key: "oldAssessmentNumber", value: oldAssessmentNumber.value });
      }
      if (mobileNumber.value) {
        queryParams.push({ key: "mobileNumber", value: mobileNumber.value });
      }
      let data = [];
      this.fetchSearchResult(queryParams, form).then((result) => {
        this.setState({
          searchResult: result,
        });
      });
    }
  };

  fetchSearchResult = async (queryParams, form) => {
    try {
      const { saveUrl, action } = form;
      console.log(saveUrl, action);
      return await httpRequest(saveUrl, action, queryParams, {});
    } catch (error) {
      const { message } = error;
      // dispatch(toggleSnackbarAndSetText(true, message, true));
      return;
    }
  };

  extractTableData = (properties) => {
    const tableData = properties.reduce((tableData, property, index) => {
      let { propertyId, oldPropertyId, address, propertyDetails } = property;
      let displayAddress = address.doorNo + "," + address.buildingName + "," + address.street;
      let name = propertyDetails[0].owners[0].name;
      let button = <Button className={"search-table-assess-pay-btn"} label={"Assess & Pay"} value={propertyId} />;
      let item = { name: name, propertyId: propertyId, oldPropertyId: oldPropertyId, address: displayAddress, action: button };
      tableData.push(item);
      return tableData;
    }, []);
    return tableData;
  };

  render() {
    console.log(this.state.data);
    const tableData = this.extractTableData(Properties);
    console.log(tableData);
    return (
      <Screen>
        <PropertySearchFormHOC history={this.props.history} onSearchClick={this.onSearchClick} />
        <PropertyTable tableData={tableData} />
      </Screen>
    );
  }
}

const mapDispatchToProps = (dispatch) => {
  return {
    displayFormErrors: (formKey) => dispatch(displayFormErrors(formKey)),
  };
};

export default connect(
  null,
  mapDispatchToProps
)(SearchProperty);

const Properties = [
  {
    auditDetails: {
      createdBy: null,
      lastModifiedBy: null,
      createdTime: 1531915357426,
      lastModifiedTime: 1531915512137,
    },
    creationReason: "NEWPROPERTY",
    occupancyDate: 100000,
    propertyDetails: [
      {
        institution: null,
        tenantId: "pb.amritsar",
        citizenInfo: {
          isPrimaryOwner: null,
          ownerShipPercentage: null,
          ownerType: null,
          institutionId: null,
          documents: null,
          relationship: null,
          id: 23416,
          uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
          userName: "9000000007",
          password: null,
          salutation: null,
          name: "testseven",
          gender: null,
          mobileNumber: "9000000007",
          emailId: "xyz@egovernments.org",
          altContactNumber: null,
          pan: null,
          aadhaarNumber: null,
          permanentAddress: null,
          permanentCity: null,
          permanentPinCode: null,
          correspondenceCity: null,
          correspondencePinCode: null,
          correspondenceAddress: null,
          active: null,
          dob: null,
          pwdExpiryDate: null,
          locale: null,
          type: "CITIZEN",
          signature: null,
          accountLocked: null,
          roles: [
            {
              id: 230,
              name: "Citizen",
              code: "CITIZEN",
              description: null,
              createdBy: null,
              createdDate: null,
              lastModifiedBy: null,
              lastModifiedDate: null,
              tenantId: null,
            },
          ],
          fatherOrHusbandName: null,
          bloodGroup: null,
          identificationMark: null,
          photo: null,
          createdBy: null,
          createdDate: null,
          lastModifiedBy: null,
          lastModifiedDate: null,
          otpReference: null,
          tenantId: "pb.amritsar",
        },
        source: "MUNICIPAL_RECORDS",
        usage: "usage",
        noOfFloors: 2,
        landArea: 10,
        buildUpArea: 8,
        units: [
          {
            id: "281fc0f0-622f-4d63-a610-aef603cad091",
            tenantId: "pb.amritsar",
            floorNo: "2",
            unitType: null,
            unitArea: 5,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 200,
          },
          {
            id: "c493ca26-9b76-4620-9725-9a1af99da115",
            tenantId: "pb.amritsar",
            floorNo: "1",
            unitType: null,
            unitArea: 10,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 100.1,
          },
        ],
        documents: [
          {
            id: "6fd8ae32-def5-4afc-a0f3-7ee8e460d715",
            documentType: "Adhar",
            fileStore: null,
            documentUid: "548850008000",
          },
        ],
        additionalDetails: {
          type: "jsonb",
          value: "null",
        },
        financialYear: "2017-18",
        propertyType: "OCCUPIEDPROPERTY",
        propertySubType: "INDEPENDENTBUILDING",
        assessmentNumber: "PB-PT-2018_07_18-000016",
        assessmentDate: 1531915357479,
        usageCategoryMajor: "NONRESIDENTIAL",
        ownershipCategory: "PRIVATE",
        subOwnershipCategory: "INDIVIDUAL",
        adhocExemption: 0,
        adhocPenalty: 0,
        owners: [
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "56fca3c4-bf62-4001-9ab0-ae399b1ad3e5",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
            userName: "9000000007",
            password: null,
            salutation: null,
            name: "testFive",
            gender: "FEMALE",
            mobileNumber: "9000000007",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539598483000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531822483000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531822483000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "59c188cd-bb69-40b8-8cfe-e4012f058a59",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "af567748-2a6c-4ea0-b346-4ef3700cfdc9",
            userName: "9000000008",
            password: null,
            salutation: null,
            name: "testeight",
            gender: "FEMALE",
            mobileNumber: "9000000008",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539691357000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531915357000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531915357000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
        ],
        auditDetails: {
          createdBy: null,
          lastModifiedBy: null,
          createdTime: 1531915357426,
          lastModifiedTime: 1531915357426,
        },
        channel: "SYSTEM",
      },
      {
        institution: null,
        tenantId: "pb.amritsar",
        citizenInfo: {
          isPrimaryOwner: null,
          ownerShipPercentage: null,
          ownerType: null,
          institutionId: null,
          documents: null,
          relationship: null,
          id: 23416,
          uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
          userName: "9000000007",
          password: null,
          salutation: null,
          name: "testseven",
          gender: null,
          mobileNumber: "9000000007",
          emailId: "xyz@egovernments.org",
          altContactNumber: null,
          pan: null,
          aadhaarNumber: null,
          permanentAddress: null,
          permanentCity: null,
          permanentPinCode: null,
          correspondenceCity: null,
          correspondencePinCode: null,
          correspondenceAddress: null,
          active: null,
          dob: null,
          pwdExpiryDate: null,
          locale: null,
          type: "CITIZEN",
          signature: null,
          accountLocked: null,
          roles: [
            {
              id: 230,
              name: "Citizen",
              code: "CITIZEN",
              description: null,
              createdBy: null,
              createdDate: null,
              lastModifiedBy: null,
              lastModifiedDate: null,
              tenantId: null,
            },
          ],
          fatherOrHusbandName: null,
          bloodGroup: null,
          identificationMark: null,
          photo: null,
          createdBy: null,
          createdDate: null,
          lastModifiedBy: null,
          lastModifiedDate: null,
          otpReference: null,
          tenantId: "pb.amritsar",
        },
        source: "MUNICIPAL_RECORDS",
        usage: "usage",
        noOfFloors: 2,
        landArea: 10,
        buildUpArea: 8,
        units: [
          {
            id: "e305ea55-89bc-42bc-9d1b-06bdd53fdddd",
            tenantId: "pb.amritsar",
            floorNo: "1",
            unitType: null,
            unitArea: 10,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 100.1,
          },
          {
            id: "1b165628-72dc-4d65-b04d-d7431324a6ff",
            tenantId: "pb.amritsar",
            floorNo: "2",
            unitType: null,
            unitArea: 5,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 200,
          },
        ],
        documents: [
          {
            id: "28ca85f3-f26b-44d6-9823-20c62d43f453",
            documentType: "Adhar",
            fileStore: null,
            documentUid: "548850008000",
          },
        ],
        additionalDetails: {
          type: "jsonb",
          value: '{"type": "jsonb", "value": "null"}',
        },
        financialYear: "2016-17",
        propertyType: "OCCUPIEDPROPERTY",
        propertySubType: "INDEPENDENTBUILDING",
        assessmentNumber: "PB-PT-2018_07_18-000017",
        assessmentDate: 1531915512163,
        usageCategoryMajor: "NONRESIDENTIAL",
        ownershipCategory: "PRIVATE",
        subOwnershipCategory: "INDIVIDUAL",
        adhocExemption: 0,
        adhocPenalty: 0,
        owners: [
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "7ceed114-7871-447b-8d1d-d8d6124ca036",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
            userName: "9000000007",
            password: null,
            salutation: null,
            name: "testFive",
            gender: "MALE",
            mobileNumber: "9000000007",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539598483000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531822483000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531822483000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "e2a1a536-00aa-4fd8-b972-fc066929021a",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "af567748-2a6c-4ea0-b346-4ef3700cfdc9",
            userName: "9000000008",
            password: null,
            salutation: null,
            name: "testeight",
            gender: "FEMALE",
            mobileNumber: "9000000008",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539691357000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531915357000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531915357000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
        ],
        auditDetails: {
          createdBy: null,
          lastModifiedBy: null,
          createdTime: 1531915512163,
          lastModifiedTime: 1531915512137,
        },
        channel: "SYSTEM",
      },
    ],
    propertyId: "PB-PT-2018_07_18-000015",
    tenantId: "pb.amritsar",
    acknowldgementNumber: "PB-PT-2018_07_18-000025",
    oldPropertyId: "oldPropertyId",
    status: "ACTIVE",
    address: {
      id: "13140674-d1d4-42f1-8511-2a796e2e93bd",
      tenantId: "pb.amritsar",
      latitude: 0,
      longitude: 0,
      addressId: null,
      addressNumber: null,
      type: "four",
      addressLine1: null,
      addressLine2: null,
      landmark: null,
      doorNo: "1",
      city: "amritsar",
      pincode: "321322",
      detail: null,
      buildingName: "Whitefield",
      street: "ITPL side road",
      locality: {
        code: "abc",
        name: null,
        label: null,
        latitude: null,
        longitude: null,
        children: null,
        materializedPath: null,
      },
    },
  },
  {
    auditDetails: {
      createdBy: null,
      lastModifiedBy: null,
      createdTime: 1531915357426,
      lastModifiedTime: 1531915512137,
    },
    creationReason: "NEWPROPERTY",
    occupancyDate: 100000,
    propertyDetails: [
      {
        institution: null,
        tenantId: "pb.amritsar",
        citizenInfo: {
          isPrimaryOwner: null,
          ownerShipPercentage: null,
          ownerType: null,
          institutionId: null,
          documents: null,
          relationship: null,
          id: 23416,
          uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
          userName: "9000000007",
          password: null,
          salutation: null,
          name: "testseven",
          gender: null,
          mobileNumber: "9000000007",
          emailId: "xyz@egovernments.org",
          altContactNumber: null,
          pan: null,
          aadhaarNumber: null,
          permanentAddress: null,
          permanentCity: null,
          permanentPinCode: null,
          correspondenceCity: null,
          correspondencePinCode: null,
          correspondenceAddress: null,
          active: null,
          dob: null,
          pwdExpiryDate: null,
          locale: null,
          type: "CITIZEN",
          signature: null,
          accountLocked: null,
          roles: [
            {
              id: 230,
              name: "Citizen",
              code: "CITIZEN",
              description: null,
              createdBy: null,
              createdDate: null,
              lastModifiedBy: null,
              lastModifiedDate: null,
              tenantId: null,
            },
          ],
          fatherOrHusbandName: null,
          bloodGroup: null,
          identificationMark: null,
          photo: null,
          createdBy: null,
          createdDate: null,
          lastModifiedBy: null,
          lastModifiedDate: null,
          otpReference: null,
          tenantId: "pb.amritsar",
        },
        source: "MUNICIPAL_RECORDS",
        usage: "usage",
        noOfFloors: 2,
        landArea: 10,
        buildUpArea: 8,
        units: [
          {
            id: "281fc0f0-622f-4d63-a610-aef603cad091",
            tenantId: "pb.amritsar",
            floorNo: "2",
            unitType: null,
            unitArea: 5,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 200,
          },
          {
            id: "c493ca26-9b76-4620-9725-9a1af99da115",
            tenantId: "pb.amritsar",
            floorNo: "1",
            unitType: null,
            unitArea: 10,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 100.1,
          },
        ],
        documents: [
          {
            id: "6fd8ae32-def5-4afc-a0f3-7ee8e460d715",
            documentType: "Adhar",
            fileStore: null,
            documentUid: "548850008000",
          },
        ],
        additionalDetails: {
          type: "jsonb",
          value: "null",
        },
        financialYear: "2017-18",
        propertyType: "OCCUPIEDPROPERTY",
        propertySubType: "INDEPENDENTBUILDING",
        assessmentNumber: "PB-PT-2018_07_18-000016",
        assessmentDate: 1531915357479,
        usageCategoryMajor: "NONRESIDENTIAL",
        ownershipCategory: "PRIVATE",
        subOwnershipCategory: "INDIVIDUAL",
        adhocExemption: 0,
        adhocPenalty: 0,
        owners: [
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "56fca3c4-bf62-4001-9ab0-ae399b1ad3e5",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
            userName: "9000000007",
            password: null,
            salutation: null,
            name: "testseven",
            gender: "FEMALE",
            mobileNumber: "9000000007",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539598483000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531822483000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531822483000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "59c188cd-bb69-40b8-8cfe-e4012f058a59",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "af567748-2a6c-4ea0-b346-4ef3700cfdc9",
            userName: "9000000008",
            password: null,
            salutation: null,
            name: "testeight",
            gender: "FEMALE",
            mobileNumber: "9000000008",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539691357000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531915357000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531915357000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
        ],
        auditDetails: {
          createdBy: null,
          lastModifiedBy: null,
          createdTime: 1531915357426,
          lastModifiedTime: 1531915357426,
        },
        channel: "SYSTEM",
      },
      {
        institution: null,
        tenantId: "pb.amritsar",
        citizenInfo: {
          isPrimaryOwner: null,
          ownerShipPercentage: null,
          ownerType: null,
          institutionId: null,
          documents: null,
          relationship: null,
          id: 23416,
          uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
          userName: "9000000007",
          password: null,
          salutation: null,
          name: "testseven",
          gender: null,
          mobileNumber: "9000000007",
          emailId: "xyz@egovernments.org",
          altContactNumber: null,
          pan: null,
          aadhaarNumber: null,
          permanentAddress: null,
          permanentCity: null,
          permanentPinCode: null,
          correspondenceCity: null,
          correspondencePinCode: null,
          correspondenceAddress: null,
          active: null,
          dob: null,
          pwdExpiryDate: null,
          locale: null,
          type: "CITIZEN",
          signature: null,
          accountLocked: null,
          roles: [
            {
              id: 230,
              name: "Citizen",
              code: "CITIZEN",
              description: null,
              createdBy: null,
              createdDate: null,
              lastModifiedBy: null,
              lastModifiedDate: null,
              tenantId: null,
            },
          ],
          fatherOrHusbandName: null,
          bloodGroup: null,
          identificationMark: null,
          photo: null,
          createdBy: null,
          createdDate: null,
          lastModifiedBy: null,
          lastModifiedDate: null,
          otpReference: null,
          tenantId: "pb.amritsar",
        },
        source: "MUNICIPAL_RECORDS",
        usage: "usage",
        noOfFloors: 2,
        landArea: 10,
        buildUpArea: 8,
        units: [
          {
            id: "e305ea55-89bc-42bc-9d1b-06bdd53fdddd",
            tenantId: "pb.amritsar",
            floorNo: "1",
            unitType: null,
            unitArea: 10,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 100.1,
          },
          {
            id: "1b165628-72dc-4d65-b04d-d7431324a6ff",
            tenantId: "pb.amritsar",
            floorNo: "2",
            unitType: null,
            unitArea: 5,
            usageCategoryMajor: "NONRESIDENTIAL",
            usageCategoryMinor: "COMMERCIAL",
            usageCategorySubMinor: "RETAIL",
            usageCategoryDetail: "GROCERYSTORE",
            occupancyType: "RENTED",
            occupancyDate: 132321,
            constructionType: "PUCCA",
            constructionSubType: "COUNTRYTILED",
            arv: 200,
          },
        ],
        documents: [
          {
            id: "28ca85f3-f26b-44d6-9823-20c62d43f453",
            documentType: "Adhar",
            fileStore: null,
            documentUid: "548850008000",
          },
        ],
        additionalDetails: {
          type: "jsonb",
          value: '{"type": "jsonb", "value": "null"}',
        },
        financialYear: "2016-17",
        propertyType: "OCCUPIEDPROPERTY",
        propertySubType: "INDEPENDENTBUILDING",
        assessmentNumber: "PB-PT-2018_07_18-000017",
        assessmentDate: 1531915512163,
        usageCategoryMajor: "NONRESIDENTIAL",
        ownershipCategory: "PRIVATE",
        subOwnershipCategory: "INDIVIDUAL",
        adhocExemption: 0,
        adhocPenalty: 0,
        owners: [
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "7ceed114-7871-447b-8d1d-d8d6124ca036",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "9f99de38-1cfb-49d6-8f08-8a00325f30ea",
            userName: "9000000007",
            password: null,
            salutation: null,
            name: "testseven",
            gender: "FEMALE",
            mobileNumber: "9000000007",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539598483000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531822483000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531822483000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
          {
            isPrimaryOwner: true,
            ownerShipPercentage: 0,
            ownerType: "WIDOW",
            institutionId: null,
            documents: [
              {
                id: "e2a1a536-00aa-4fd8-b972-fc066929021a",
                documentType: "adhar",
                fileStore: null,
                documentUid: "123456789999",
              },
            ],
            relationship: null,
            id: null,
            uuid: "af567748-2a6c-4ea0-b346-4ef3700cfdc9",
            userName: "9000000008",
            password: null,
            salutation: null,
            name: "testeight",
            gender: "FEMALE",
            mobileNumber: "9000000008",
            emailId: "xyz@egovernments.org",
            altContactNumber: null,
            pan: null,
            aadhaarNumber: "111111111111",
            permanentAddress: "InstitutionCorespondenceAddress",
            permanentCity: "Kaikoo",
            permanentPinCode: null,
            correspondenceCity: null,
            correspondencePinCode: null,
            correspondenceAddress: null,
            active: true,
            dob: null,
            pwdExpiryDate: 1539691357000,
            locale: null,
            type: "CITIZEN",
            signature: null,
            accountLocked: false,
            roles: [
              {
                id: 230,
                name: "Citizen",
                code: "CITIZEN",
                description: null,
                createdBy: null,
                createdDate: null,
                lastModifiedBy: null,
                lastModifiedDate: null,
                tenantId: null,
              },
            ],
            fatherOrHusbandName: "Karan",
            bloodGroup: null,
            identificationMark: null,
            photo: null,
            createdBy: "23287",
            createdDate: 1531915357000,
            lastModifiedBy: "23287",
            lastModifiedDate: 1531915357000,
            otpReference: null,
            tenantId: "pb.amritsar",
          },
        ],
        auditDetails: {
          createdBy: null,
          lastModifiedBy: null,
          createdTime: 1531915512163,
          lastModifiedTime: 1531915512137,
        },
        channel: "SYSTEM",
      },
    ],
    propertyId: "PB-PT-2018_07_18-000014",
    tenantId: "pb.amritsar",
    acknowldgementNumber: "PB-PT-2018_07_18-000025",
    oldPropertyId: "oldPropertyId",
    status: "ACTIVE",
    address: {
      id: "13140674-d1d4-42f1-8511-2a796e2e93bd",
      tenantId: "pb.amritsar",
      latitude: 0,
      longitude: 0,
      addressId: null,
      addressNumber: null,
      type: "four",
      addressLine1: null,
      addressLine2: null,
      landmark: null,
      doorNo: "1",
      city: "amritsar",
      pincode: "321322",
      detail: null,
      buildingName: "Springfield",
      street: "Sarjapur Road",
      locality: {
        code: "abc",
        name: null,
        label: null,
        latitude: null,
        longitude: null,
        children: null,
        materializedPath: null,
      },
    },
  },
];
