export const AUTHENTICATING = "AUTHENTICATING";
export const AUTHENTICATED = "AUTHENTICATED";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED";
export const LOGOUT = "LOGOUT";
