const actionList = {
  // citizen: [
  //   {
  //     id: 1535,
  //     name: "PropertyType",
  //     url: "url",
  //     displayName: "Home",
  //     orderNumber: 1,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Home",
  //     navigationURL: "property-tax",
  //     leftIcon: { action: "action", name: "home" },
  //     rightIcon: "",
  //   },
  //   {
  //     id: 1536,
  //     name: "PropertySubType",
  //     url: "url",
  //     displayName: "Information",
  //     orderNumber: 2,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Information",
  //     navigationURL: "mdms/PropertyTax/PropertySubType",
  //     leftIcon: { action: "action", name: "info" },
  //     rightIcon: "",
  //   },
  //   {
  //     id: 1537,
  //     name: "ConstructionType",
  //     url: "url",
  //     displayName: "Payments",
  //     orderNumber: 3,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Payments",
  //     navigationURL: "mdms/PropertyTax/ConstructionType",
  //     leftIcon: { action: "custom", name: "rupee" },
  //     rightIcon: "",
  //   },
  //   {
  //     id: 1538,
  //     name: "ConstructionSubType",
  //     url: "url",
  //     displayName: "Apply",
  //     orderNumber: 4,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Apply",
  //     navigationURL: "mdms/PropertyTax/ConstructionSubType",
  //     leftIcon: { action: "content", name: "send" },
  //     rightIcon: "",
  //   },
  // ],
  citizen: [
    {
      id: 1535,
      name: "Home",
      url: "url",
      displayName: "Home",
      orderNumber: 1,
      enabled: true,
      serviceCode: "CS",
      code: "null",
      path: "Home",
      navigationURL: "",
      leftIcon: { action: "action", name: "home" },
      rightIcon: "",
    },
    {
      id: 1536,
      name: "Information",
      url: "url",
      displayName: "Information",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Information",
      navigationURL: "all-complaints",
      leftIcon: { action: "action", name: "info" },
      rightIcon: "",
    },
    {
      id: 1537,
      name: "Payments",
      url: "url",
      displayName: "Payments",
      orderNumber: 3,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Payments",
      navigationURL: "all-complaints",
      leftIcon: { action: "custom", name: "rupee" },
      rightIcon: "",
    },
    {
      id: 1538,
      name: "ConstructionSubType",
      url: "url",
      displayName: "Apply",
      orderNumber: 4,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Apply",
      navigationURL: "all-complaints",
      leftIcon: { action: "content", name: "send" },
      rightIcon: "",
    },
    {
      id: 1538,
      name: "ConstructionSubType",
      url: "url",
      displayName: "Property Tax",
      orderNumber: 4,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Apply",
      navigationURL: "property-tax",
      leftIcon: { action: "content", name: "send" },
      rightIcon: "",
    },
  ],

  employee: [
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "Open Complaints",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Home",
      navigationURL: "all-complaints",
      leftIcon: { action: "custom", name: "open-complaints" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "Closed Complaints",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Home",
      navigationURL: "closed-complaints",
      leftIcon: { action: "custom", name: "closed-complaints" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "Departments",
      url: "url",
      displayName: "Departments",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Departments",
      navigationURL: "report/rainmaker-pgr/DepartmentWiseReport",
      leftIcon: { action: "action", name: "assignment" },
    },
    {
      id: 1535,
      name: "AssigningOfficers",
      url: "url",
      displayName: "Assigning Officers",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Assigning Officers",
      navigationURL: "report/rainmaker-pgr/AOWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "Source",
      url: "url",
      displayName: "Source",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Source",
      navigationURL: "report/rainmaker-pgr/SourceWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "ULBEmployees",
      url: "url",
      displayName: "ULB Employees",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.ULB Employees",
      navigationURL: "report/rainmaker-pgr/FunctionaryWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "ULBEmployees",
      url: "url",
      displayName: "Complaint Types",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Complaint Types",
      navigationURL: "report/rainmaker-pgr/ComplaintTypeWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
  ],
  ao: [
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "Open Complaints",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Home",
      navigationURL: "all-complaints",
      leftIcon: { action: "custom", name: "open-complaints" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "Closed Complaints",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Home",
      navigationURL: "closed-complaints",
      leftIcon: { action: "custom", name: "closed-complaints" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "Departments",
      url: "url",
      displayName: "Departments",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Departments",
      navigationURL: "report/rainmaker-pgr/DepartmentWiseReport",
      leftIcon: { action: "action", name: "assignment" },
    },
    {
      id: 1535,
      name: "AssigningOfficers",
      url: "url",
      displayName: "Assigning Officers",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Assigning Officers",
      navigationURL: "report/rainmaker-pgr/AOWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "Source",
      url: "url",
      displayName: "Source",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Source",
      navigationURL: "report/rainmaker-pgr/SourceWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "ULBEmployees",
      url: "url",
      displayName: "ULB Employees",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.ULB Employees",
      navigationURL: "report/rainmaker-pgr/FunctionaryWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "ULBEmployees",
      url: "url",
      displayName: "Complaint Types",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "PGR Reports.Complaint Types",
      navigationURL: "report/rainmaker-pgr/ComplaintTypeWiseReport",
      leftIcon: { action: "action", name: "assignment" },
      rightIcon: "",
    },
  ],
  csr: [
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "All Complaints",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Home",
      navigationURL: "all-complaints",
      leftIcon: { action: "custom", name: "open-complaints" },
      rightIcon: "",
    },
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "Create Complaint",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "create-complaint",
      navigationURL: "create-complaint",
      leftIcon: { action: "content", name: "add" },
      rightIcon: "",
    },
  ],
};

export default actionList;
