const actionList = {
  // citizen: [
  //   {
  //     id: 1535,
  //     name: "PropertyType",
  //     url: "url",
  //     displayName: "Home",
  //     orderNumber: 1,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Home",
  //     navigationURL: "property-tax",
  //     leftIcon: { action: "action", name: "home" },
  //     rightIcon: "",
  //   },
  //   {
  //     id: 1536,
  //     name: "PropertySubType",
  //     url: "url",
  //     displayName: "Information",
  //     orderNumber: 2,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Information",
  //     navigationURL: "mdms/PropertyTax/PropertySubType",
  //     leftIcon: { action: "action", name: "info" },
  //     rightIcon: "",
  //   },
  //   {
  //     id: 1537,
  //     name: "ConstructionType",
  //     url: "url",
  //     displayName: "Payments",
  //     orderNumber: 3,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Payments",
  //     navigationURL: "mdms/PropertyTax/ConstructionType",
  //     leftIcon: { action: "custom", name: "rupee" },
  //     rightIcon: "",
  //   },
  //   {
  //     id: 1538,
  //     name: "ConstructionSubType",
  //     url: "url",
  //     displayName: "Apply",
  //     orderNumber: 4,
  //     enabled: true,
  //     serviceCode: "PT",
  //     code: "null",
  //     path: "Apply",
  //     navigationURL: "mdms/PropertyTax/ConstructionSubType",
  //     leftIcon: { action: "content", name: "send" },
  //     rightIcon: "",
  //   },
  // ],
  citizen: [
    {
      id: 1535,
      name: "Home",
      url: "url",
      displayName: "Home",
      orderNumber: 1,
      enabled: true,
      serviceCode: "CS",
      code: "null",
      path: "Home",
      navigationURL: "/citizen",
      leftIcon: { action: "action", name: "home" },
      rightIcon: "",
    },
    {
      id: 1536,
      name: "Information",
      url: "url",
      displayName: "Information",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Information",
      navigationURL: "/citizen",
      leftIcon: { action: "action", name: "info" },
      rightIcon: "",
    },
    {
      id: 1537,
      name: "Payments",
      url: "url",
      displayName: "Payments",
      orderNumber: 3,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Payments",
      navigationURL: "/citizen",
      leftIcon: { action: "custom", name: "rupee" },
      rightIcon: "",
    },
    {
      id: 1538,
      name: "ConstructionSubType",
      url: "url",
      displayName: "Apply",
      orderNumber: 4,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Apply",
      navigationURL: "mdms/PropertyTax/ConstructionSubType",
      leftIcon: { action: "content", name: "send" },
      rightIcon: "",
    },
  ],
  employee: [
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "Home",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Home",
      navigationURL: "property-tax",
      leftIcon: { action: "action", name: "home" },
      rightIcon: "",
    },
    {
      id: 1536,
      name: "PropertySubType",
      url: "url",
      displayName: "Information",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Information",
      navigationURL: "mdms/PropertyTax/PropertySubType",
      leftIcon: { action: "action", name: "info" },
      rightIcon: "",
    },
    {
      id: 1537,
      name: "ConstructionType",
      url: "url",
      displayName: "Payments",
      orderNumber: 3,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Payments",
      navigationURL: "mdms/PropertyTax/ConstructionType",
      leftIcon: { action: "custom", name: "rupee" },
      rightIcon: "",
    },
    {
      id: 1538,
      name: "ConstructionSubType",
      url: "url",
      displayName: "Apply",
      orderNumber: 4,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Apply",
      navigationURL: "mdms/PropertyTax/ConstructionSubType",
      leftIcon: { action: "content", name: "send" },
      rightIcon: "",
    },
  ],
  csr: [
    {
      id: 1535,
      name: "PropertyType",
      url: "url",
      displayName: "Home",
      orderNumber: 1,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Home",
      navigationURL: "property-tax",
      leftIcon: { action: "action", name: "home" },
      rightIcon: "",
    },
    {
      id: 1536,
      name: "PropertySubType",
      url: "url",
      displayName: "Information",
      orderNumber: 2,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Information",
      navigationURL: "mdms/PropertyTax/PropertySubType",
      leftIcon: { action: "action", name: "info" },
      rightIcon: "",
    },
    {
      id: 1537,
      name: "ConstructionType",
      url: "url",
      displayName: "Payments",
      orderNumber: 3,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Payments",
      navigationURL: "mdms/PropertyTax/ConstructionType",
      leftIcon: { action: "custom", name: "rupee" },
      rightIcon: "",
    },
    {
      id: 1538,
      name: "ConstructionSubType",
      url: "url",
      displayName: "Apply",
      orderNumber: 4,
      enabled: true,
      serviceCode: "PT",
      code: "null",
      path: "Apply",
      navigationURL: "mdms/PropertyTax/ConstructionSubType",
      leftIcon: { action: "content", name: "send" },
      rightIcon: "",
    },
  ],
};

export default actionList;
