"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var PROPERTY_FETCH_PENDING = exports.PROPERTY_FETCH_PENDING = "PROPERTY_FETCH_PENDING";
var PROPERTY_FETCH_COMPLETE = exports.PROPERTY_FETCH_COMPLETE = "PROPERTY_FETCH_COMPLETE";
var PROPERTY_FETCH_ERROR = exports.PROPERTY_FETCH_ERROR = "PROPERTY_FETCH_ERROR";

var DRAFT_FETCH_PENDING = exports.DRAFT_FETCH_PENDING = "DRAFT_FETCH_PENDING";
var DRAFT_FETCH_COMPLETE = exports.DRAFT_FETCH_COMPLETE = "DRAFT_FETCH_COMPLETE";
var DRAFT_FETCH_ERROR = exports.DRAFT_FETCH_ERROR = "DRAFT_FETCH_ERROR";

var PG_FETCH_PENDING = exports.PG_FETCH_PENDING = "PG_FETCH_PENDING";
var PG_FETCH_COMPLETE = exports.PG_FETCH_COMPLETE = "PG_FETCH_COMPLETE";
var PG_FETCH_ERROR = exports.PG_FETCH_ERROR = "PG_FETCH_ERROR";