"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var PROPERTY_FETCH_PENDING = exports.PROPERTY_FETCH_PENDING = "PROPERTY_FETCH_PENDING";
var PROPERTY_FETCH_COMPLETE = exports.PROPERTY_FETCH_COMPLETE = "PROPERTY_FETCH_COMPLETE";
var PROPERTY_FETCH_ERROR = exports.PROPERTY_FETCH_ERROR = "PROPERTY_FETCH_ERROR";