"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var ASSESSMENT_FETCH_PENDING = exports.ASSESSMENT_FETCH_PENDING = "ASSESSMENT_FETCH_PENDING";
var ASSESSMENT_FETCH_COMPLETE = exports.ASSESSMENT_FETCH_COMPLETE = "ASSESSMENT_FETCH_COMPLETE";
var ASSESSMENT_FETCH_ERROR = exports.ASSESSMENT_FETCH_ERROR = "ASSESSMENT_FETCH_ERROR";