export const COMMENT_ADD_PENDING = "COMMENT_ADD_PENDING";
export const COMMENT_ADD_COMPLETE = "COMMENT_ADD_COMPLETE";
export const COMMENT_ADD_ERROR = "COMMENT_ADD_ERROR";
export const COMMENTS_FETCH_PENDING = "COMMENTS_FETCH_PENDING";
export const COMMENTS_FETCH_COMPLETE = "COMMENTS_FETCH_COMPLETE";
export const COMMENTS_FETCH_ERROR = "COMMENTS_FETCH_ERROR";
