"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var COMPLAINTS_FETCH_PENDING = exports.COMPLAINTS_FETCH_PENDING = "COMPLAINTS_FETCH_PENDING";
var COMPLAINTS_FETCH_COMPLETE = exports.COMPLAINTS_FETCH_COMPLETE = "COMPLAINTS_FETCH_COMPLETE";
var COMPLAINTS_FETCH_ERROR = exports.COMPLAINTS_FETCH_ERROR = "COMPLAINTS_FETCH_ERROR";
var COMPLAINTS_CATEGORIES_FETCH_SUCCESS = exports.COMPLAINTS_CATEGORIES_FETCH_SUCCESS = "COMPLAINTS_CATEGORIES_FETCH_SUCCESS";
var COMPLAINTS_CATEGORIES_FETCH_ERROR = exports.COMPLAINTS_CATEGORIES_FETCH_ERROR = "COMPLAINTS_CATEGORIES_FETCH_ERROR";