export const searchSampleResponse = () => {
  let res = {
    ResponseInfo: {
      apiId: "Rainmaker",
      ver: ".01",
      ts: null,
      resMsgId: "uief87324",
      msgId: "20170310130900|en_IN",
      status: "successful"
    },
    FireNOCs: [
      {
        fid: "101",
        tenantId: "pb.amritsar",
        firenocnumber: "",
        dateofapplied: "1556649000000",
        firenocdetailsid: "201",
        action: "INITIATE",
        applicationnumber: "PB-NOC-201",
        firenoctype: "New",
        applicationdate: 1556649000000,
        financialyear: "2018-19",
        issueddate: "1557154107155",
        validfrom: "1546300800",
        validto: "1577836800",
        channel: "web",
        buildingid: "B1",
        name: "Building 1",
        nooffloors: "1",
        noofbasements: "1",
        ownerid: "301",
        ownertype: "SINGLE",
        useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
        relationship: "FATHER",
        status: "INITIATED",
        fireNOCDetails: {
          id: "201",
          applicationStatus: "INITIATED",
          fireNOCType: "New",
          firestationId: "",
          applicationDate: "1556649000000",
          financialYear: "2018-19",
          issuedDate: "1557154107155",
          validFrom: "1546300800",
          validTo: "1577836800",
          action: "INITIATE",
          channel: "web",
          noOfBuildings: "MULTIPLE",
          buildings: [
            {
              id: "B1",
              name: "DSRRH",
              noOfFloors: "1",
              noOfBasements: "1",
              applicationDocuments: []
            },
            {
              id: "B3",
              noOfFloors: "1",
              noOfBasements: "1",
              applicationDocuments: []
            }
          ],
          propertyDetails: {},
          applicantDetails: {
            owners: [
              {
                id: "301",
                useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
                ownerType: "SINGLE",
                relationship: "FATHER",
                fatherOrHusbandName: "",
                password: "",
                salutation: "",
                name: "Shreya NayaK",
                gender: "FEMALE",
                mobileNumber: "9686987977",
                emailId: "",
                altContactNumber: "",
                pan: "",
                dob: "1992-11-11",
                aadhaarNumber: null,
                permanentAddress: "new Street",
                permanentCity: "pb.amritsar",
                permanentPincode: null,
                correspondenceCity: null,
                correspondenceAddress: null
              },
              {
                id: "305",
                useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
                ownerType: "SINGLE",
                relationship: "FATHER",
                fatherOrHusbandName: "",
                password: "",
                salutation: "",
                name: "Shreya NayaK",
                gender: "FEMALE",
                mobileNumber: "9686987977",
                emailId: "",
                altContactNumber: "",
                pan: "",
                dob: "1992-11-11",
                aadhaarNumber: null,
                permanentAddress: "new Street",
                permanentCity: "pb.amritsar",
                permanentPincode: null,
                correspondenceCity: null,
                correspondenceAddress: null
              }
            ],
            additionalDetail: {}
          },
          additionalDetail: {},
          auditDetails: {}
        }
      },
      {
        fid: "102",
        tenantId: "pb.amritsar",
        firenocnumber: "",
        dateofapplied: "1556649000000",
        firenocdetailsid: "202",
        action: "INITIATE",
        applicationnumber: "PB-NOC-202",
        firenoctype: "New",
        applicationdate: 1556649000000,
        financialyear: "2018-19",
        issueddate: "1557154107156",
        validfrom: "1546300800",
        validto: "1577836800",
        channel: "web",
        buildingid: "B2",
        name: "Building 2",
        nooffloors: "1",
        noofbasements: "1",
        ownerid: "302",
        ownertype: "SINGLE",
        useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
        relationship: "FATHER",
        status: "INITIATED",
        fireNOCDetails: {
          id: "202",
          applicationStatus: "INITIATED",
          fireNOCType: "New",
          firestationId: "",
          applicationDate: "1556649000000",
          financialYear: "2018-19",
          issuedDate: "1557154107156",
          validFrom: "1546300800",
          validTo: "1577836800",
          action: "INITIATE",
          channel: "web",
          noOfBuildings: "",
          buildings: [
            {
              id: "B2",
              noOfFloors: "1",
              noOfBasements: "1",
              applicationDocuments: []
            }
          ],
          propertyDetails: {},
          applicantDetails: {
            owners: [
              {
                id: "302",
                useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
                ownerType: "SINGLE",
                relationship: "FATHER",
                fatherOrHusbandName: "",
                password: "",
                salutation: "",
                name: "Shreya NayaK",
                gender: "FEMALE",
                mobileNumber: "9686987977",
                emailId: "",
                altContactNumber: "",
                pan: "",
                dob: "1992-11-11",
                aadhaarNumber: null,
                permanentAddress: "new Street",
                permanentCity: "pb.amritsar",
                permanentPincode: null,
                correspondenceCity: null,
                correspondenceAddress: null
              },
              {
                id: "306",
                useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
                ownerType: "SINGLE",
                relationship: "FATHER",
                fatherOrHusbandName: "",
                password: "",
                salutation: "",
                name: "Shreya NayaK",
                gender: "FEMALE",
                mobileNumber: "9686987977",
                emailId: "",
                altContactNumber: "",
                pan: "",
                dob: "1992-11-11",
                aadhaarNumber: null,
                permanentAddress: "new Street",
                permanentCity: "pb.amritsar",
                permanentPincode: null,
                correspondenceCity: null,
                correspondenceAddress: null
              }
            ],
            additionalDetail: {}
          },
          additionalDetail: {},
          auditDetails: {}
        }
      },
      {
        fid: "105",
        tenantId: "pb.amritsar",
        firenocnumber: "",
        dateofapplied: "1556649000000",
        firenocdetailsid: "205",
        action: "INITIATE",
        applicationnumber: "PB-NOC-205",
        firenoctype: "New",
        applicationdate: 1556649000000,
        financialyear: "2018-19",
        issueddate: "1556649000000",
        validfrom: "1556649000000",
        validto: "1556649000000",
        channel: "Web",
        buildingid: "B5",
        name: "Building 5",
        nooffloors: "2",
        noofbasements: "1",
        ownerid: "o5",
        ownertype: "",
        useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
        relationship: "FATHER",
        status: "INITIATED",
        fireNOCDetails: {
          id: "205",
          applicationStatus: "INITIATED",
          fireNOCType: "New",
          firestationId: "",
          applicationDate: "1556649000000",
          financialYear: "2018-19",
          issuedDate: "1556649000000",
          validFrom: "1556649000000",
          validTo: "1556649000000",
          action: "INITIATE",
          channel: "Web",
          noOfBuildings: "",
          buildings: [
            {
              id: "B5",
              noOfFloors: "2",
              noOfBasements: "1",
              applicationDocuments: []
            }
          ],
          propertyDetails: {},
          applicantDetails: {
            owners: [
              {
                id: "o5",
                useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
                ownerType: "",
                relationship: "FATHER",
                fatherOrHusbandName: "",
                password: "",
                salutation: "",
                name: "Shreya NayaK",
                gender: "FEMALE",
                mobileNumber: "9686987977",
                emailId: "",
                altContactNumber: "",
                pan: "",
                dob: "1992-11-11",
                aadhaarNumber: null,
                permanentAddress: "new Street",
                permanentCity: "pb.amritsar",
                permanentPincode: null,
                correspondenceCity: null,
                correspondenceAddress: null
              }
            ],
            additionalDetail: {}
          },
          additionalDetail: {},
          auditDetails: {}
        }
      },
      {
        fid: "106",
        tenantId: "pb.amritsar",
        firenocnumber: "",
        dateofapplied: "1556821800000",
        firenocdetailsid: "206",
        action: "INITIATE",
        applicationnumber: "PB-NOC-20",
        firenoctype: "New",
        applicationdate: 1556821800000,
        financialyear: "2018-19",
        issueddate: "1556821800000",
        validfrom: "1556821800000",
        validto: "1556821800000",
        channel: "Web",
        buildingid: "B6",
        name: "Building 6",
        nooffloors: "2",
        noofbasements: "1",
        ownerid: "o6",
        ownertype: "",
        useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
        relationship: "FATHER",
        status: "INITIATED",
        fireNOCDetails: {
          id: "206",
          applicationStatus: "INITIATED",
          fireNOCType: "New",
          firestationId: "",
          applicationDate: "1556821800000",
          financialYear: "2018-19",
          issuedDate: "1556821800000",
          validFrom: "1556821800000",
          validTo: "1556821800000",
          action: "INITIATE",
          channel: "Web",
          noOfBuildings: "",
          buildings: [
            {
              id: "B6",
              noOfFloors: "2",
              noOfBasements: "1",
              applicationDocuments: []
            }
          ],
          propertyDetails: {},
          applicantDetails: {
            owners: [
              {
                id: "o6",
                useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
                ownerType: "",
                relationship: "FATHER",
                fatherOrHusbandName: "",
                password: "",
                salutation: "",
                name: "Shreya NayaK",
                gender: "FEMALE",
                mobileNumber: "9686987977",
                emailId: "",
                altContactNumber: "",
                pan: "",
                dob: "1992-11-11",
                aadhaarNumber: null,
                permanentAddress: "new Street",
                permanentCity: "pb.amritsar",
                permanentPincode: null,
                correspondenceCity: null,
                correspondenceAddress: null
              }
            ],
            additionalDetail: {}
          },
          additionalDetail: {},
          auditDetails: {}
        }
      },
      {
        fid: "107",
        tenantId: "pb.amritsar",
        firenocnumber: "",
        dateofapplied: "1556908200000",
        firenocdetailsid: "207",
        action: "INITIATE",
        applicationnumber: "PB-NOC-207",
        firenoctype: "New",
        applicationdate: 1556908200000,
        financialyear: "2018-19",
        issueddate: "1556908200000",
        validfrom: "1556908200000",
        validto: "1556908200000",
        channel: "Web",
        buildingid: "B7",
        name: "Building 7",
        nooffloors: "2",
        noofbasements: "1",
        ownerid: "o7",
        ownertype: "",
        useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
        relationship: "FATHER",
        status: "INITIATED",
        fireNOCDetails: {
          id: "207",
          applicationStatus: "INITIATED",
          fireNOCType: "New",
          firestationId: "",
          applicationDate: "1556908200000",
          financialYear: "2018-19",
          issuedDate: "1556908200000",
          validFrom: "1556908200000",
          validTo: "1556908200000",
          action: "INITIATE",
          channel: "Web",
          noOfBuildings: "",
          buildings: [
            {
              id: "B7",
              noOfFloors: "2",
              noOfBasements: "1",
              applicationDocuments: []
            }
          ],
          propertyDetails: {},
          applicantDetails: {
            owners: [
              {
                id: "o7",
                useruuid: "5417dbb7-14b9-4be2-ac46-ce2decb30444",
                ownerType: "",
                relationship: "FATHER",
                fatherOrHusbandName: "",
                password: "",
                salutation: "",
                name: "Shreya NayaK",
                gender: "FEMALE",
                mobileNumber: "9686987977",
                emailId: "",
                altContactNumber: "",
                pan: "",
                dob: "1992-11-11",
                aadhaarNumber: null,
                permanentAddress: "new Street",
                permanentCity: "pb.amritsar",
                permanentPincode: null,
                correspondenceCity: null,
                correspondenceAddress: null
              }
            ],
            additionalDetail: {}
          },
          additionalDetail: {},
          auditDetails: {}
        }
      },
      {
        fid: "6a80fcb4-3767-4bd4-b01b-7177107a334a",
        tenantId: "pb.amritsar",
        firenocnumber: null,
        dateofapplied: null,
        firenocdetailsid: "03d2cae0-b608-4a13-9974-56b7eb73c129",
        action: "INITIATE",
        applicationnumber: "PB-NOC-100",
        firenoctype: "string",
        applicationdate: 12131238,
        financialyear: "string",
        issueddate: null,
        validfrom: "0",
        validto: "0",
        channel: "COUNTER",
        buildingid: "ab011f2c-58ca-4b6c-9231-e36b8aad7a61",
        name: "string",
        nooffloors: "0",
        noofbasements: "0",
        ownerid: "f71c0468-0f1f-458d-bfb5-0cad82011287",
        ownertype: "string",
        useruuid: null,
        relationship: "FATHER",
        status: "INITIATED",
        fireNOCDetails: {
          id: "03d2cae0-b608-4a13-9974-56b7eb73c129",
          applicationStatus: "INITIATED",
          fireNOCType: "string",
          firestationId: "",
          applicationDate: "12131238",
          financialYear: "string",
          issuedDate: null,
          validFrom: "0",
          validTo: "0",
          action: "INITIATE",
          channel: "COUNTER",
          noOfBuildings: "",
          buildings: [
            {
              id: "ab011f2c-58ca-4b6c-9231-e36b8aad7a61",
              noOfFloors: "0",
              noOfBasements: "0",
              applicationDocuments: []
            }
          ],
          propertyDetails: {},
          applicantDetails: { owners: [null], additionalDetail: {} },
          additionalDetail: {},
          auditDetails: {}
        }
      }
    ]
  };
  return res;
};
