"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SET_DROPDOWN_DATA = exports.SET_DROPDOWN_DATA = "SET_DROPDOWN_DATA";
var EMPLOYEE_FETCH_SUCCESS = exports.EMPLOYEE_FETCH_SUCCESS = "EMPLOYEE_FETCH_SUCCESS";
var EMPLOYEE_FETCH_ERROR = exports.EMPLOYEE_FETCH_ERROR = "EMPLOYEE_FETCH_ERROR";
var CITIZEN_FETCH_SUCCESS = exports.CITIZEN_FETCH_SUCCESS = "CITIZEN_FETCH_SUCCESS";
var CITIZEN_FETCH_ERROR = exports.CITIZEN_FETCH_ERROR = "CITIZEN_FETCH_ERROR";
var MDMS_FETCH_SUCCESS = exports.MDMS_FETCH_SUCCESS = "MDMS_FETCH_SUCCESS";
var MDMS_FETCH_ERROR = exports.MDMS_FETCH_ERROR = "MDMS_FETCH_ERROR";