"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SHOW_MENU = exports.SHOW_MENU = "SHOW_MENU";
var CHANGE_BOTTOM_NAVIGATION_INDEX = exports.CHANGE_BOTTOM_NAVIGATION_INDEX = "CHANGE_BOTTOM_NAVIGATION_INDEX";
var SHOW_DIALOG = exports.SHOW_DIALOG = "SHOW_DIALOG";
var SHOW_TOAST = exports.SHOW_TOAST = "SHOW_TOAST";
var SET_LOGO = exports.SET_LOGO = "SET_LOGO";
var SET_APP_NAME = exports.SET_APP_NAME = "SET_APP_NAME";
var SET_ROUTE = exports.SET_ROUTE = "SET_ROUTE";
var ADD_LOCALIZATION = exports.ADD_LOCALIZATION = "ADD_LOCALIZATION";
var UPDATE_LOCALIZATION = exports.UPDATE_LOCALIZATION = "UPDATE_LOCALIZATION";
var SET_USER_INFO = exports.SET_USER_INFO = "SET_USER_INFO";
var SET_USER_CURRENT_LOCATION = exports.SET_USER_CURRENT_LOCATION = "SET_USER_CURRENT_LOCATION";